### ISSUE TITLE
Angular-Wrapper

### ISSUE THREAD

**Issue by mcilurzo** [sbb-design-systems/lyne-angular#4]
- create 1:1 wrapper
- create testability

Following tasks:
- [x] Angular wrapper: Create sample page and run tests on it
- [x] sbb-design-systems/lyne-angular#3
- [x] sbb-design-systems/lyne-angular#5
- [x] sbb-design-systems/lyne-angular#7
- [x] sbb-design-systems/lyne-angular#6

**Comment by kyubisation** [comment]
There are more issues, but these are tracked in their own dedicated issues.
